# Based on https://blog.codeship.com/running-rails-development-environment-docker/
app:
  build: .
  environment:
    - DATABASE_HOST=postgres
  command: /app/script/server
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.4.11
  ports:
    - "5432"
