# Based on https://blog.codeship.com/running-rails-development-environment-docker/
app:
  build: .
  environment:
    - DATABASE_HOST=mysql
  command: /app/script/server
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - mysql
mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=password
  ports:
    - "3306"
